from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from report_agent.config import CONFIG
from report_agent.core.account_state import AccountState, normalize_date_key
from report_agent.core.data_loader import DataLoader


TODAY = "20260901"
ETF_PREFIXES = ("15", "16", "50", "51", "52", "56", "58")


def normalize_date(value: object) -> str:
    return normalize_date_key(value)


def stocks_only(frame: pd.DataFrame) -> pd.DataFrame:
    if frame.empty or "证券代码" not in frame.columns:
        return frame.copy()
    filtered = frame.copy()
    codes = filtered["证券代码"].astype(str).str.split(".").str[0].str.replace(r"\D", "", regex=True).str.zfill(6)
    return filtered.loc[~codes.str.startswith(ETF_PREFIXES)].copy()


def load_today_frames(loader: DataLoader, account_id: str, day: str) -> tuple[dict, pd.DataFrame, pd.DataFrame]:
    account_file = loader._find_input_file(account_id, "account")
    deals_file = loader._find_input_file(account_id, "deals")
    positions_file = loader._find_input_file(account_id, "positions")

    account_raw = loader._read_csv(account_file)
    account_info = loader._extract_account_info(account_raw)

    deals_df = loader._normalize_deals(loader._read_csv(deals_file))
    if not deals_df.empty and "成交日期" in deals_df.columns:
        dates = deals_df["成交日期"].astype(str).map(normalize_date)
        deals_df = deals_df.loc[dates == day].copy()
    deals_df = stocks_only(deals_df)

    positions_df = loader._normalize_positions(loader._read_csv(positions_file))
    positions_df = stocks_only(positions_df)

    return account_info, deals_df, positions_df


def pick_source_payload(account_dir: Path, target_day: str) -> tuple[dict, Path]:
    target = account_dir / f"{target_day}.json"
    if target.exists():
        payload = json.loads(target.read_text(encoding="utf-8"))
        return payload, target

    files = sorted(p for p in account_dir.glob("*.json") if p.stem.isdigit() and p.stem < target_day)
    if not files:
        raise RuntimeError(f"No cache source file found for {account_dir}")
    src = files[-1]
    payload = json.loads(src.read_text(encoding="utf-8"))
    return payload, src


def run_for_account(account_id: str, day: str) -> None:
    account_dir = Path(CONFIG["cache_dir"]) / account_id
    account_dir.mkdir(parents=True, exist_ok=True)
    target_path = account_dir / f"{day}.json"

    existing_target = json.loads(target_path.read_text(encoding="utf-8")) if target_path.exists() else None
    nav_source_payload, nav_source_path = pick_source_payload(account_dir, day)

    prev_files = sorted(p for p in account_dir.glob("*.json") if p.stem.isdigit() and p.stem < day)
    has_prev = bool(prev_files)
    if has_prev:
        prev_payload = json.loads(prev_files[-1].read_text(encoding="utf-8"))
    else:
        prev_payload = existing_target or nav_source_payload
    state = AccountState.from_dict(prev_payload)

    initial_capital = float(CONFIG.get("initial_capital", {}).get(account_id, state.initial_capital))
    state.initial_capital = initial_capital

    loader = DataLoader(CONFIG["data_dir"])
    account_info, deals_df, positions_df = load_today_frames(loader, account_id, day)

    if has_prev:
        state.update(day, account_info, deals_df, positions_df)
    # Always force-write today's snapshots from real CSV, including empty-day cases.
    state.trade_history[day] = deals_df.copy()
    state.position_history[day] = positions_df.copy()
    state.current_positions = positions_df.copy()

    stock_mv = float(pd.to_numeric(positions_df.get("市值", pd.Series(dtype=float)), errors="coerce").fillna(0.0).sum())
    repo_mv = float(sum(float(item.get("principal", 0.0)) for item in state.repo_positions))
    day_entries = [entry for entry in list(state.cash_ledger.get(day, [])) if str(entry.get("type", "")) != "snapshot_reconcile"]
    cash_balance = float(day_entries[-1].get("balance_after", state.cash_balance)) if day_entries else float(state.cash_balance)
    total_asset = float(cash_balance + stock_mv + repo_mv)
    profit = float(total_asset - initial_capital)

    state.current_stock_mv = stock_mv
    state.current_repo_mv = repo_mv
    state.current_asset = total_asset
    state.current_profit = profit
    state.cash_balance = cash_balance

    # Keep stock-only cash ledger as generated by filtered trades; no full-account snapshot reconcile.
    state.cash_ledger[day] = day_entries

    base_equity = float(state.base_total_equity if state.base_total_equity else (initial_capital or 1.0))
    nav_today = float(total_asset / base_equity) if base_equity else 1.0

    # Preserve nav_history strictly before today from the existing target (if any), otherwise from source payload.
    baseline_nav = (existing_target or nav_source_payload).get("nav_history", {})
    preserved_nav = {
        normalize_date(k): float(v)
        for k, v in baseline_nav.items()
        if normalize_date(k) < day
    }
    preserved_nav[day] = float(nav_today)
    state.nav_history = pd.Series(preserved_nav, dtype=float).sort_index()

    if not state.nav_history.empty:
        state.peak_nav = float(state.nav_history.max())
        state.peak_date = str(state.nav_history.idxmax())

    output = state.to_dict()
    target_path.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")

    print(
        "UPDATED",
        account_id,
        "target=",
        target_path,
        "nav_source=",
        nav_source_path.name,
        "deals_rows=",
        len(deals_df),
        "positions_rows=",
        len(positions_df),
        "nav_today=",
        float(nav_today),
        "total_asset=",
        float(total_asset),
    )


def main() -> None:
    for account_id in CONFIG.get("initial_capital", {}).keys():
        run_for_account(str(account_id), TODAY)


if __name__ == "__main__":
    main()
